### ISSUE TITLE
Статус выполненности задачи

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/tech#1]
Добавить возможность вставить статус задачи:
Готова
В процессе
Не начата

**Comment by schaman** [comment]
Не прописана

**Comment by schaman** [comment]
Очевидно, есть два статуса:

Статус постановки
- Новая
- Требует уточнения
- Поставлена

Статус выполнения
- Нет исполнителя
- Не начата
- Выполняется
- Готова

**Comment by kirilldudinsky** [comment]
Мне кажется, не нужен статус постановки.
Новая - ну и новая, ну и ок. Если есть статус "Не начата", то она "Новая". 
Если есть статус "Выполняется", значит, она точно "Поставлена".
"Требует уточнения", это скорее не статус, а задача к текущему списку задач - доделать список, или уточнить такие-то шаги. 

Но смотри сам.

**Comment by schaman** [comment]
А пустой статус может быть? Или сразу при создании задачи присваивать «не начата»?
