### ISSUE TITLE
Не могу добавить новое направление

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/tech#10]
![2014-11-18 1 15 29](https://cloud.githubusercontent.com/assets/9354450/5080459/7aa27788-6ec0-11e4-9604-2f91d8fb2b99.png)
![2014-11-18 1 15 35](https://cloud.githubusercontent.com/assets/9354450/5080458/7aa27ada-6ec0-11e4-84ac-1870183ce3c9.png)

**Comment by schaman** [comment]
Можешь временно пользоваться кнопкой «добавить» тут: http://tech.icoach.io/tech/task/

Исправлю чуть позже

**Comment by schaman** [comment]
Готово
