### ISSUE TITLE
Не выводится список вложенных тасков

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/tech#11]
Есть вот так
![2014-11-21 19 29 31](https://cloud.githubusercontent.com/assets/9354450/5147304/d8128a9c-71b4-11e4-80cf-a5b313c690af.png)

А хотелось бы вот так
![2014-11-21 19 31 05](https://cloud.githubusercontent.com/assets/9354450/5147325/f34b62c0-71b4-11e4-8e7b-d2a0b5310f3d.png)

Т.е. чтобы когда я нажимаю на ветвь "ПроЛюбовь" мне выводился список тасков для этого направления.

**Comment by schaman** [comment]
fixed
