### ISSUE TITLE
Нарушается иерархия таксов, когда я создаю новую цепочку

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/tech#12]
Создаю цепочку и указываю, какими тасками ее наполнить
![2014-11-21 19 33 26](https://cloud.githubusercontent.com/assets/9354450/5147375/6eae3ffa-71b5-11e4-825b-04cfd997ab38.png)
Получается вот так
![2014-11-21 19 33 43](https://cloud.githubusercontent.com/assets/9354450/5147387/8c9fc682-71b5-11e4-9d21-89f033cbcd2a.png)

А должно быть вот так

![2014-11-21 19 33 54](https://cloud.githubusercontent.com/assets/9354450/5147390/90d6f3c4-71b5-11e4-8602-0c25f7c777e6.png)

**Comment by schaman** [comment]
fixed
