### ISSUE TITLE
При заполнении новой цепочки тасками теряется текст в поле Text в тасках

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/tech#13]
В теке было вот так
![2014-11-21 19 36 30](https://cloud.githubusercontent.com/assets/9354450/5147442/f84887c0-71b5-11e4-9e7f-f81ec50b2cbd.png)

А после добавления новой цепочки и заполнения её тасками из тека текст не отображается

![2014-11-21 19 40 48](https://cloud.githubusercontent.com/assets/9354450/5147507/514b6e32-71b6-11e4-8cef-8a58855ed53a.png)

**Comment by schaman** [comment]
fixed
