### ISSUE TITLE
Хочу менять вложенность ветвей

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/tech#7]
Хочу сделать ветвь "Цепочка - не понятно, что делать" дочерней ветвью ветви "Создать направление", а такой возможности нет
![2014-11-17 22 47 05](https://cloud.githubusercontent.com/assets/9354450/5078293/e831aeaa-6eab-11e4-84ca-6641cee64721.png)

**Comment by schaman** [comment]
При слишком большой вложенности эта штука не работает. Сделано специальное ограничение, чтобы ты не закапывался слишком глубоко, а делал отдельные технологии.
![max-nesting-level](https://cloud.githubusercontent.com/assets/1928852/5079157/fa64715e-6ec2-11e4-9e03-638be17527b6.gif)
