### ISSUE TITLE
Не могу удалить tech

### ISSUE THREAD

**Issue by kirilldudinsky** [schaman/tech#8]
![2014-11-17 22 51 21](https://cloud.githubusercontent.com/assets/9354450/5078354/62f5232e-6eac-11e4-9437-f2ee5cfb5c8b.png)
![2014-11-17 22 51 26](https://cloud.githubusercontent.com/assets/9354450/5078355/62f88c44-6eac-11e4-8d71-3c1a6e8985b8.png)
![2014-11-17 22 51 29](https://cloud.githubusercontent.com/assets/9354450/5078353/62f51f64-6eac-11e4-992a-778698dde70a.png)
![2014-11-17 22 51 31](https://cloud.githubusercontent.com/assets/9354450/5078356/62f8e9aa-6eac-11e4-9616-68ee68536115.png)

**Comment by schaman** [comment]
Готово
